// --------------------------------------------------------------------
// AUTOGENERATED DURING BUILD, DO NOT EDIT
// --------------------------------------------------------------------
//

import UIKit

/**
* The list of icons that can be rendered from the style kit.
*/

@objc(WRStyleKitIcon)
public enum StyleKitIcon: Int {

    /// Represents the data necessary to render the icons.
    public typealias RenderingProperties = (renderingMethod: (UIColor) -> Void, originalSize: CGFloat)

    case trash
    case brush
    case cameraSwitch
    case ball
    case settingsAdvanced
    case markdownH1
    case markdownBold
    case personalProfile
    case flag
    case bellWithStrikethrough
    case phone
    case folderList
    case microphoneWithStrikethrough
    case statusBusy
    case library
    case forwardArrow
    case microphone
    case reply
    case speaker
    case backArrow
    case send
    case effectChurch
    case missedCall
    case fullScreen
    case conversation
    case alien
    case downArrow
    case search
    case minus
    case hourglass
    case endCall
    case timeoutWeek
    case timeoutMinute
    case block
    case plusCircled
    case location
    case document
    case paperclip
    case statusAway
    case about
    case spinner
    case cross
    case hamburger
    case plus
    case settingsSupport
    case alerts
    case mention
    case effectRollercoaster
    case effectBalloon
    case asterisk
    case flower
    case cameraShutter
    case recordDot
    case locationPin
    case archive
    case cameraLens
    case cake
    case person
    case envelope
    case devices
    case videoMessage
    case markdownCode
    case markdownItalic
    case addPerson
    case effectJellyfish
    case emoji
    case redo
    case typingDots
    case stopRecording
    case undo
    case movie
    case settingsOptions
    case forwardArrowWithDot
    case checkmark
    case bot
    case markdownH3
    case pause
    case markdownH2
    case copy
    case exclamationMark
    case timeoutDay
    case restore
    case browser
    case legalholdactive
    case activeSearch
    case liked
    case export
    case externalLink
    case legalholdpending
    case save
    case recentList
    case markdownNumberList
    case guest
    case timeoutMonth
    case car
    case clearInput
    case networkCondition
    case markdownToggle
    case eye
    case eyeDisable
    case gif
    case ellipsis
    case pencil
    case photo
    case createConversation
    case gear
    case link
    case exclamationMarkCircle
    case effectRabbit
    case backArrowWithDot
    case team
    case disclosureIndicator
    case clock
    case videoCall
    case statusAvailable
    case longDownArrow
    case markdownBulletList
    case crown
    case ping
    case timeoutSecond
    case like
    case play
    case timeoutYear
    case timeoutHour
    
    case upArrow
    case scan
    case addFriend
    case addressBook
    case makeConversation
    case coreFriends
    case lockSVG

   
//    case settingAccount                  = 0x4000
    case settingPhone                    = 0x4001
    case settingEmail                    = 0x4002
    case settingAccountManager           = 0x4003
    case settingSetting                  = 0x4004
    case lock                            = 0x4006
    case pngCallAudio                    = 0x4007
    case pngCallVideo                    = 0x4008
    case autoreplyDrawin                 = 0x4009
    case autoreplyAI                     = 0x4010
    case autoreplyZuChongZhi             = 0x4011
    case settingScanLoginWeb             = 0x4013
    case settingSecurity                 = 0x4014
    case settingPhoto                    = 0x4015
    case secretLogo                      = 0x4016
    case star                            = 0x4017
    case settingAccount                  = 0x4018
    case settingDevice                   = 0x4019
    case settingOption                   = 0x4020
    case settingAdvanced                 = 0x4021
    case settingAbout                    = 0x4022
    case settingBackup                   = 0x4023
    case settingDarkMode                 = 0x4024
    case settingLanguage                 = 0x4025
    case settingContact                  = 0x4026
    case settingPrivacy                  = 0x4027
    
    /// The properties to use to render the icon.
    var renderingProperties: RenderingProperties {
        switch self {
        case .trash: return (WireStyleKit.drawIcon_trash_64pt, 64)
        case .brush: return (WireStyleKit.drawIcon_brush_64pt, 64)
        case .cameraSwitch: return (WireStyleKit.drawIcon_cameraSwitch_64pt, 64)
        case .ball: return (WireStyleKit.drawIcon_ball_64pt, 64)
        case .settingsAdvanced: return (WireStyleKit.drawIcon_settingsAdvanced_64pt, 64)
        case .markdownH1: return (WireStyleKit.drawIcon_markdownH1_64pt, 64)
        case .markdownBold: return (WireStyleKit.drawIcon_markdownBold_64pt, 64)
        case .personalProfile: return (WireStyleKit.drawIcon_personalProfile_64pt, 64)
        case .flag: return (WireStyleKit.drawIcon_flag_64pt, 64)
        case .bellWithStrikethrough: return (WireStyleKit.drawIcon_bellWithStrikethrough_64pt, 64)
        case .phone: return (WireStyleKit.drawIcon_phone_64pt, 64)
        case .microphoneWithStrikethrough: return (WireStyleKit.drawIcon_microphoneWithStrikethrough_64pt, 64)
        case .statusBusy: return (WireStyleKit.drawIcon_statusBusy_64pt, 64)
        case .library: return (WireStyleKit.drawIcon_library_64pt, 64)
        case .forwardArrow: return (WireStyleKit.drawIcon_forwardArrow_64pt, 64)
        case .microphone: return (WireStyleKit.drawIcon_microphone_64pt, 64)
        case .reply: return (WireStyleKit.drawIcon_reply_64pt, 64)
        case .speaker: return (WireStyleKit.drawIcon_speaker_64pt, 64)
        case .backArrow: return (WireStyleKit.drawIcon_backArrow_64pt, 64)
        case .send: return (WireStyleKit.drawIcon_send_64pt, 64)
        case .effectChurch: return (WireStyleKit.drawIcon_effectChurch_64pt, 64)
        case .missedCall: return (WireStyleKit.drawIcon_missedCall_64pt, 64)
        case .fullScreen: return (WireStyleKit.drawIcon_fullScreen_64pt, 64)
        case .conversation: return (WireStyleKit.drawIcon_conversation_64pt, 64)
        case .alien: return (WireStyleKit.drawIcon_alien_64pt, 64)
        case .downArrow: return (WireStyleKit.drawIcon_downArrow_64pt, 64)
        case .upArrow: return (WireStyleKit.drawIcon_0x814_32pt, 64)
        case .search: return (WireStyleKit.drawIcon_search_64pt, 64)
        case .minus: return (WireStyleKit.drawIcon_minus_64pt, 64)
        case .hourglass: return (WireStyleKit.drawIcon_hourglass_64pt, 64)
        case .endCall: return (WireStyleKit.drawIcon_endCall_64pt, 64)
        case .timeoutWeek: return (WireStyleKit.drawIcon_timeoutWeek_64pt, 64)
        case .timeoutMinute: return (WireStyleKit.drawIcon_timeoutMinute_64pt, 64)
        case .block: return (WireStyleKit.drawIcon_block_64pt, 64)
        case .plusCircled: return (WireStyleKit.drawIcon_plusCircled_64pt, 64)
        case .location: return (WireStyleKit.drawIcon_location_64pt, 64)
        case .document: return (WireStyleKit.drawIcon_document_64pt, 64)
        case .paperclip: return (WireStyleKit.drawIcon_paperclip_64pt, 64)
        case .statusAway: return (WireStyleKit.drawIcon_statusAway_64pt, 64)
        case .about: return (WireStyleKit.drawIcon_about_64pt, 64)
        case .spinner: return (WireStyleKit.drawIcon_spinner_64pt, 64)
        case .cross: return (WireStyleKit.drawIcon_cross_64pt, 64)
        case .hamburger: return (WireStyleKit.drawIcon_hamburger_64pt, 64)
        case .plus: return (WireStyleKit.drawIcon_plus_64pt, 64)
        case .settingsSupport: return (WireStyleKit.drawIcon_settingsSupport_64pt, 64)
        case .alerts: return (WireStyleKit.drawIcon_alerts_64pt, 64)
        case .mention: return (WireStyleKit.drawIcon_mention_64pt, 64)
        case .effectRollercoaster: return (WireStyleKit.drawIcon_effectRollercoaster_64pt, 64)
        case .effectBalloon: return (WireStyleKit.drawIcon_effectBalloon_64pt, 64)
        case .asterisk: return (WireStyleKit.drawIcon_asterisk_64pt, 64)
        case .flower: return (WireStyleKit.drawIcon_flower_64pt, 64)
        case .cameraShutter: return (WireStyleKit.drawIcon_cameraShutter_64pt, 64)
        case .recordDot: return (WireStyleKit.drawIcon_recordDot_64pt, 64)
        case .locationPin: return (WireStyleKit.drawIcon_locationPin_64pt, 64)
        case .archive: return (WireStyleKit.drawIcon_archive_64pt, 64)
        case .cameraLens: return (WireStyleKit.drawIcon_cameraLens_64pt, 64)
        case .cake: return (WireStyleKit.drawIcon_cake_64pt, 64)
        case .person: return (WireStyleKit.drawIcon_person_64pt, 64)
        case .envelope: return (WireStyleKit.drawIcon_envelope_64pt, 64)
        case .devices: return (WireStyleKit.drawIcon_devices_64pt, 64)
        case .videoMessage: return (WireStyleKit.drawIcon_videoMessage_64pt, 64)
        case .markdownCode: return (WireStyleKit.drawIcon_markdownCode_64pt, 64)
        case .markdownItalic: return (WireStyleKit.drawIcon_markdownItalic_64pt, 64)
        case .addPerson: return (WireStyleKit.drawIcon_addPerson_64pt, 64)
        case .effectJellyfish: return (WireStyleKit.drawIcon_effectJellyfish_64pt, 64)
        case .emoji: return (WireStyleKit.drawIcon_emoji_64pt, 64)
        case .redo: return (WireStyleKit.drawIcon_redo_64pt, 64)
        case .typingDots: return (WireStyleKit.drawIcon_typingDots_64pt, 64)
        case .stopRecording: return (WireStyleKit.drawIcon_stopRecording_64pt, 64)
        case .undo: return (WireStyleKit.drawIcon_undo_64pt, 64)
        case .movie: return (WireStyleKit.drawIcon_movie_64pt, 64)
        case .settingsOptions: return (WireStyleKit.drawIcon_settingsOptions_64pt, 64)
        case .forwardArrowWithDot: return (WireStyleKit.drawIcon_forwardArrowWithDot_64pt, 64)
        case .checkmark: return (WireStyleKit.drawIcon_checkmark_64pt, 64)
        case .bot: return (WireStyleKit.drawIcon_bot_64pt, 64)
        case .markdownH3: return (WireStyleKit.drawIcon_markdownH3_64pt, 64)
        case .pause: return (WireStyleKit.drawIcon_pause_64pt, 64)
        case .markdownH2: return (WireStyleKit.drawIcon_markdownH2_64pt, 64)
        case .copy: return (WireStyleKit.drawIcon_copy_64pt, 64)
        case .exclamationMark: return (WireStyleKit.drawIcon_exclamationMark_64pt, 64)
        case .timeoutDay: return (WireStyleKit.drawIcon_timeoutDay_64pt, 64)
        case .restore: return (WireStyleKit.drawIcon_restore_48pt, 48)
        case .browser: return (WireStyleKit.drawIcon_browser_64pt, 64)
        case .legalholdactive: return (WireStyleKit.drawIcon_legalholdactive_64pt, 64)
        case .activeSearch: return (WireStyleKit.drawIcon_activeSearch_64pt, 64)
        case .liked: return (WireStyleKit.drawIcon_liked_64pt, 64)
        case .export: return (WireStyleKit.drawIcon_export_64pt, 64)
        case .externalLink: return (WireStyleKit.drawIcon_externalLink_64pt, 64)
        case .legalholdpending: return (WireStyleKit.drawIcon_legalholdpending_64pt, 64)
        case .save: return (WireStyleKit.drawIcon_save_64pt, 64)
        case .markdownNumberList: return (WireStyleKit.drawIcon_markdownNumberList_64pt, 64)
        case .guest: return (WireStyleKit.drawIcon_guest_64pt, 64)
        case .timeoutMonth: return (WireStyleKit.drawIcon_timeoutMonth_64pt, 64)
        case .car: return (WireStyleKit.drawIcon_car_64pt, 64)
        case .clearInput: return (WireStyleKit.drawIcon_clearInput_64pt, 64)
        case .networkCondition: return (WireStyleKit.drawIcon_networkCondition_64pt, 64)
        case .markdownToggle: return (WireStyleKit.drawIcon_markdownToggle_64pt, 64)
        case .eye: return (WireStyleKit.drawIcon_eye_64pt, 64)
        case .eyeDisable: return (WireStyleKit.drawIcon_eyeDisable_64pt, 64)
        case .gif: return (WireStyleKit.drawIcon_gif_64pt, 64)
        case .ellipsis: return (WireStyleKit.drawIcon_ellipsis_64pt, 64)
        case .pencil: return (WireStyleKit.drawIcon_pencil_64pt, 64)
        case .photo: return (WireStyleKit.drawIcon_photo_64pt, 64)
        case .createConversation: return (WireStyleKit.drawIcon_createConversation_64pt, 64)
        case .gear: return (WireStyleKit.drawIcon_gear_64pt, 64)
        case .link: return (WireStyleKit.drawIcon_link_64pt, 64)
        case .exclamationMarkCircle: return (WireStyleKit.drawIcon_exclamationMarkCircle_64pt, 64)
        case .effectRabbit: return (WireStyleKit.drawIcon_effectRabbit_64pt, 64)
        case .backArrowWithDot: return (WireStyleKit.drawIcon_backArrowWithDot_64pt, 64)
        case .team: return (WireStyleKit.drawIcon_team_64pt, 64)
        case .disclosureIndicator: return (WireStyleKit.drawIcon_disclosureIndicator_64pt, 64)
        case .clock: return (WireStyleKit.drawIcon_clock_64pt, 64)
        case .videoCall: return (WireStyleKit.drawIcon_videoCall_64pt, 64)
        case .statusAvailable: return (WireStyleKit.drawIcon_statusAvailable_64pt, 64)
        case .longDownArrow: return (WireStyleKit.drawIcon_longDownArrow_64pt, 64)
        case .markdownBulletList: return (WireStyleKit.drawIcon_markdownBulletList_64pt, 64)
        case .crown: return (WireStyleKit.drawIcon_crown_64pt, 64)
        case .ping: return (WireStyleKit.drawIcon_ping_64pt, 64)
        case .timeoutSecond: return (WireStyleKit.drawIcon_timeoutSecond_64pt, 64)
        case .like: return (WireStyleKit.drawIcon_like_64pt, 64)
        case .play: return (WireStyleKit.drawIcon_play_64pt, 64)
        case .timeoutYear: return (WireStyleKit.drawIcon_timeoutYear_64pt, 64)
        case .timeoutHour: return (WireStyleKit.drawIcon_timeoutHour_64pt, 64)
        case .scan: return (WireStyleKit.drawIcon_scan_64pt, 64)
        case .addFriend: return (WireStyleKit.drawIcon_addFriend_64pt, 64)
        case .addressBook: return (WireStyleKit.drawIcon_addressBook_64pt, 64)
        case .makeConversation: return (WireStyleKit.drawIcon_makeConversation_64pt, 64)
        case .coreFriends: return (WireStyleKit.drawIcon_coreFriends_64pt, 64)
        case .folderList: return (WireStyleKit.drawIcon_folderList_64pt, 64)
        case .recentList: return (WireStyleKit.drawIcon_recentList_64pt, 64)
        case .lockSVG: return (WireStyleKit.drawIcon_lockSVG_64pt, 64)
        default: return (WireStyleKit.drawLogo, 64)
        }
    }
    
    
    public var isImage: Bool {
        self.rawValue >= StyleKitIcon.settingPhone.rawValue
    }
    
    public var image: UIImage? {
        guard isImage else { return nil }
        return UIImage(named: String(format: "%03x", rawValue))
    }
}
